### ISSUE TITLE
Creating Autocommands or functions in rust to be called on vim side

### ISSUE THREAD

**Issue by Kethku** [KillTheMule/nvim-rs#14]
I'm struggling to understand how one might define a function in rust which can be called on the neovim side. The other plugin systems seem to work by defining a spec and having the user call UpdateRemotePlugins after spec has been registered to define function stubs which allow calling to the remote plugins.

For a gui this seems decidedly not ideal as the gui would have to run neovim once to register and again after registering. I'm wondering if there is a simpler way which let me register autocommands for option tracking and the like without having to go the full remote plugin route.

Do you have any advice?

**Comment by KillTheMule** [comment]
You'll need to use `rpcrequest` or `rpcnotify`, and then check for the method name in the handler. See [the example](https://github.com/KillTheMule/nvim-rs/blob/master/examples/scorched_earth.rs#L55) as well as how it is [called from nvim](https://github.com/boxofrox/neovim-scorched-earth/blob/master/autoload/scorchedEarth.vim#L47-L72). Or am I misunderstanding you?

**Comment by Kethku** [comment]
that was a useful hint. THanks!
