### ISSUE TITLE
Errors compiling code with Compat<ChildStdin> on master

### ISSUE THREAD

**Issue by smolck** [KillTheMule/nvim-rs#29]
On 0.2, I'm able to compile, say, my [spotify.nvim](https://github.com/smolck/spotify.nvim) plugin just fine.

However, if I change the Cargo.toml line for nvim-rs in spotify.nvim to use latest master from git (`nvim-rs = { git = "https://github.com/killthemule/nvim-rs", features = ["use_tokio"] }`), I get these errors:

```bash
error[E0277]: the trait bound `tokio::io::Stdout: tokio::io::async_write::AsyncWrite` is not satisfied
  --> src/main.rs:51:45
   |
51 |     async fn try_init_spotify(&self, nvim: &Neovim<Compat<Stdout>>) -> Result<(), String> {
   |                                             ^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio::io::Stdout`
   |
  ::: /Users/smolck/.cargo/git/checkouts/nvim-rs-be8ec18c7fa103f5/9eeea5a/src/neovim.rs:50:6
   |
50 |   W: AsyncWrite + Send + Unpin + 'static,
   |      ---------- required by this bound in `Neovim`
   |
   = note: required because of the requirements on the impl of `futures::AsyncWrite` for `nvim_rs::compat::tokio::Compat<tokio::io::Stdout>`

error[E0277]: the trait bound `tokio::io::Stdout: tokio::io::async_write::AsyncWrite` is not satisfied
   --> src/main.rs:148:75
    |
148 |     async fn handle_notify(&self, name: String, args: Vec<Value>, neovim: Neovim<Compat<Stdout>>) {
    |                                                                           ^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio::io::Stdout`
    |
   ::: /Users/smolck/.cargo/git/checkouts/nvim-rs-be8ec18c7fa103f5/9eeea5a/src/neovim.rs:50:6
    |
50  |   W: AsyncWrite + Send + Unpin + 'static,
    |      ---------- required by this bound in `Neovim`
    |
    = note: required because of the requirements on the impl of `futures::AsyncWrite` for `nvim_rs::compat::tokio::Compat<tokio::io::Stdout>`

error[E0277]: the trait bound `tokio::io::Stdout: tokio::io::async_write::AsyncWrite` is not satisfied
   --> src/main.rs:212:17
    |
212 |         neovim: Neovim<Compat<Stdout>>,
    |                 ^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio::io::Stdout`
    |
   ::: /Users/smolck/.cargo/git/checkouts/nvim-rs-be8ec18c7fa103f5/9eeea5a/src/neovim.rs:50:6
    |
50  |   W: AsyncWrite + Send + Unpin + 'static,
    |      ---------- required by this bound in `Neovim`
    |
    = note: required because of the requirements on the impl of `futures::AsyncWrite` for `nvim_rs::compat::tokio::Compat<tokio::io::Stdout>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `spotify-nvim` due to 3 previous errors
```

Which is weird to me? Is this due to some change to nvim-rs, and I need to modify my code to fix it (if so, what might that look like?), or is this a bug with nvim-rs?

I *think* the commit which broke things was https://github.com/KillTheMule/nvim-rs/commit/3ee4328898b8c71b15903b1180a6782dd9673de2 fwiw/if that's helpful, although I could be wrong (note that the commit before that, https://github.com/KillTheMule/nvim-rs/commit/545f61ad5d9444563e89adef6d9afb9cae82e362, doesn't compile either, but with different errors so I think that commit can be ignored).

**Comment by KillTheMule** [comment]
That'a a tokio version mismatch. You're depending on 0.2, which means you're using `Stdout-0.2`, which does not implement `AsyncWrite-1.1.1`, which is what nvim-rs needs, depending on tokio-1.1.1. I suggest you upgrade your plugin to use the newer tokio version, should be easy enough this early in the project :) Let me know if that works out, or if that unfeasible for some reason I can't see.

**Comment by smolck** [comment]
Aha, thank you very much! That works. I don't remember where I got the 0.2 version for tokio . . . that's really outdated xD
