### ISSUE TITLE
Please publish alpha version

### ISSUE THREAD

**Issue by alopatindev** [KillTheMule/nvim-rs#35]
Can we have current version (`v0.2.1-alpha.0`) published on crates.io?

I can't publish my crate with current version of nvim-rs because it's not on crates.io:

```
$ grep nvim-rs Cargo.toml
nvim-rs = { git = "https://github.com/KillTheMule/nvim-rs", rev = "c9bef85e7f538148842cd618d4cdf7f4b330f92a", features = ["use_tokio"] }
$ cargo publish
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `nvim-rs` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

Thanks.

**Comment by KillTheMule** [comment]
Ha, ok, I think I'll just make a new major version 0.3., since the only blocking issue was https://github.com/KillTheMule/nvim-rs/issues/31, but it does not seem a problem anymore. Sounds ok? I think I can get to it tomorrow.

**Comment by alopatindev** [comment]
Yeah, thanks.

**Comment by KillTheMule** [comment]
I did publish 0.3.0, please let me know if I borked anything in the release process :)

**Comment by alopatindev** [comment]
Thanks, works for me!
