### ISSUE TITLE
Missing buf_set_mark (need API regeneration)

### ISSUE THREAD

**Issue by mattscamp** [KillTheMule/nvim-rs#38]
Need buf_set_mark in a project which seems to be missing from the current API.

https://neovim.io/doc/user/api.html#nvim_buf_set_mark()

**Comment by KillTheMule** [comment]
Ok, yeah, we have a binding generator script that lets us automatically add all the new API functions, we just need to use it and make a release. Will do so soon :)

**Comment by mattscamp** [comment]
Much appreciated @KillTheMule !

**Comment by KillTheMule** [comment]
This is now merged into master, I'll push a new release later.
