### ISSUE TITLE
set_option uses nvim_buf_set_option instead of nvim_set_option 

### ISSUE THREAD

**Issue by Kethku** [KillTheMule/nvim-rs#43]
Given that it doesn't pass a buffer id, I think this is a no-op. Not sure though

**Comment by KillTheMule** [comment]
So there are [3 instances](https://docs.rs/nvim-rs/0.4.0/nvim_rs/?search=set_option) of a `set_option` function. You probably mean the method on `Buffer`? It does [use `nvim_buf_set_option`](https://docs.rs/nvim-rs/0.4.0/src/nvim_rs/neovim_api.rs.html#262-276) indeed, but it also passes the buffer id. Do you have something going wrong?

**Comment by Kethku** [comment]
I have no idea what i was on about here
